services:
  store_db:
    image: mysql:8.0
    container_name: store_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: store
      MYSQL_USER: store
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - store_db_data:/var/lib/mysql
    networks:
      - app-network

  store_spring:
    build: .
    container_name: store_spring
    depends_on:
      - store_db
    environment:
      TZ: Asia/Seoul
      DATABASE_URL: mysql://store:${MYSQL_PASSWORD}@store_db:3306/store
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  store_db_data:
    driver: local

networks:
  app-network:
    driver: bridge