spring:
  application:
    name: store
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://store_db:3306/store
    username: store
    password: store2025

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

grpc:
  client:
    member-grpc-server:
      address: static://member-spring:9090
      negotiation-type: plaintext
      enable-keep-alive: true